export const agents = [
  {
    name: "Justin Brewer",
    email: "justin@greenhubinc.com",
    role: "Admin",
    status: "Active",
    commissionNotes: "Admin profile. Commission varies by account.",
  },
  {
    name: "Nicholas Sanchez",
    email: "nick@greenhubinc.com",
    role: "Agent",
    status: "Active",
    commissionNotes: "Uses account-level commission structure notes.",
  },
  {
    name: "Rob Sinn",
    email: "rob@paynex.net",
    role: "Agent",
    status: "Active",
    commissionNotes: "Review account-level POB and revenue share details.",
  },
  {
    name: "Mark Suchy",
    email: "mark@greenhubinc.com",
    role: "Agent",
    status: "Active",
    commissionNotes: "Commission notes stored for admin review only.",
  },
];

export const accounts = [
  {
    merchant: "Prime Wellness",
    platform: "ElitePay – Adyen",
    status: "Active",
    agent: "Nicholas Sanchez",
    volume: "$82,400",
    residual: "$1,248",
    netProfit: "$2,840",
    equipment: "$180",
  },
  {
    merchant: "Oakline Retail",
    platform: "Linked2Pay – Avidia",
    status: "Active",
    agent: "Rob Sinn",
    volume: "$54,100",
    residual: "$842",
    netProfit: "$1,940",
    equipment: "$0",
  },
  {
    merchant: "Harbor Med Spa",
    platform: "Paybotx – Fiserv",
    status: "Paused",
    agent: "Mark Suchy",
    volume: "$31,900",
    residual: "$420",
    netProfit: "$1,120",
    equipment: "$95",
  },
];

export const agentResiduals = [
  {
    merchant: "Prime Wellness",
    platform: "ElitePay – Adyen",
    month: "June 2026",
    status: "Finalized",
    volume: "$82,400",
    residual: "$1,248",
    netProfit: "$2,840",
    equipment: "$180",
    greenhubPobBuyRate: "$3.00",
    agentCommissionStructure: "50% net profit share",
    surcharge: "$240",
    rebate: "$0",
    profitPerTransaction: "$2.55",
    greenhubPobProfitPerTransaction: "$1.20",
    transactions: "489",
    pobNetProfit: "$587",
    notes: "Strong month. No merchant exceptions.",
  },
  {
    merchant: "Oakline Retail",
    platform: "Linked2Pay – Avidia",
    month: "June 2026",
    status: "Finalized",
    volume: "$54,100",
    residual: "$842",
    netProfit: "$1,940",
    equipment: "$0",
    greenhubPobBuyRate: "$2.75",
    agentCommissionStructure: "45% net profit share",
    surcharge: "$160",
    rebate: "$35",
    profitPerTransaction: "$2.30",
    greenhubPobProfitPerTransaction: "$1.05",
    transactions: "366",
    pobNetProfit: "$384",
    notes: "Rebate applied for June volume.",
  },
  {
    merchant: "Harbor Med Spa",
    platform: "Paybotx – Fiserv",
    month: "June 2026",
    status: "Finalized",
    volume: "$31,900",
    residual: "$420",
    netProfit: "$1,120",
    equipment: "$95",
    greenhubPobBuyRate: "$2.50",
    agentCommissionStructure: "Flat residual schedule",
    surcharge: "$105",
    rebate: "$0",
    profitPerTransaction: "$1.90",
    greenhubPobProfitPerTransaction: "$0.80",
    transactions: "221",
    pobNetProfit: "$177",
    notes: "Equipment cost withheld this period.",
  },
];

export const platforms = [
  "Best Rate",
  "Best Rate – Nuvei",
  "ElitePay",
  "ElitePay – Adyen",
  "Linked2Pay",
  "Linked2Pay – Avidia",
  "Paybotx",
  "Paybotx – Fiserv",
  "Ellacash",
  "Greenway POB",
  "Paynex",
  "Valmar",
];
